#!/bin/bash
#CIT-470 Project 2
#Instructor: Darci Guriel
#Team 4: Christopher Polly, Andrew Dahlenburg, Jakob Banta, Nischaya Shrestha
#Author: Jakob Banta
# Finalizes Monit Configuration

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
  echo "Usage: basename $0 [The script must be ran as followed: ./monit_config_script 'Your Server IP' ]" | tee -a monit-setup.log ; exit 0 ;
else

#Removes default monit cfg file, downloads modified version and creates a backup
echo "Configuring Monit..." | tee -a monit-setup.log && rm /etc/monitrc >&1 >> monit-setup.log ; wget -O monitrc https://raw.githubusercontent.com/cit470g4/Proj3/main/c_monitrc | tee -a monit-setup.log ; mv monitrc /etc/monitrc && cp /etc/monitrc /etc/monitrc.bak >&1 >> monit-setup.log && chmod 600 /etc/monitrc >&1 >> monit-setup.log &&

#Passes script arguments to the monit configuration file
sed -i "s/root@localhost/root@$1/g" /etc/monitrc >&1 >> monit-setup.log &&

#restart monit service
echo "Restarting Monit service..." | tee -a monit-setup.log && systemctl restart monit >&1 >> monit-setup.log && echo "Configuration complete!" | tee -a monit-setup.log

#appends the serverIP to the syslog cfg file for remote logging
wget -O monitrc https://raw.githubusercontent.com/cit470g4/Proj3/main/c_rsyslog.conf | tee -a monit-setup.log ; mv rsyslog.conf /etc/rsyslog.conf && cp /etc/rsyslog.conf /etc/rsyslog.conf.bak >&1 >> monit-setup.log && chmod 600 /etc/rsyslog.conf >&1 >> monit-setup.log && echo "Configuring remote monitoring..." | tee -a monit-setup.log && sed -i "s/#. @@remote-host:514/. @$1:514/g" /etc/rsyslog.conf >&1 >> monit-setup.log && systemctl restart rsyslog >&1 >> monit-setup.log && echo "Setup complete!" | tee -a monit-setup.log

#Configure firewall for syslog and monit.
firewall-cmd --zone=public --add-port=514/udp --permanent | tee -a monit-setup.log ; firewall-cmd --zone=public --add-port=2812/tcp --permanent | tee -a monit-setup.log ; firewall-cmd --reload | tee -a monit-setup.log

fi

