#!/bin/bash
#CIT-470 Project 3
#Instructor: Darci Guriel
#Team 4: Christopher Polly, Andrew Dahlenburg, Jakob Banta, Nischaya Shrestha
#Author: Jakob Banta
#Test Server Monit Configuration

echo "Installing required packages..." && yum -y install stress >> /var/log/server-test.log && echo "Packages installed." &&

#Kill SSH
echo "Testing SSH..." ; systemctl stop sshd ; sleep 10 ; monit summary | grep SSH ; echo "SSH testing complete!"

#Kill syslog
echo "Testing syslog..." ; systemctl stop rsyslog ; sleep 10 ; monit summary | grep syslog ; echo "syslog testing complete!"

#Kill NFS-Server
echo "Testing NFS server..." ; systemctl stop nfs ; sleep 10 ; monit summary | grep NFS ; echo "NFS-Server testing complete!"

#Kill LDAP-Server
echo "Testing LDAP server..." ; systemctl stop slapd ; sleep 10 ; monit summary | grep LDAP ; echo "LDAP-Server testing complete!"

#Overload CPU and MEM with stress tool
echo "Testing CPU and memory usage..." ; stress --vm-bytes 256MB --cpu 100 --timeout 60s >&1 >> /var/log/server-test.log ; monit summary | grep localhost ; echo "CPU and MEM testing complete!"

#Test hard drive alarm
echo "Testing disk usage.." ; dd if=/dev/zero of=/dev/diskhog bs=1M count=100000 2>&1 >> /var/log/server-test.log ; sleep 20 ; monit summary | grep HOME ; monit summary | grep ROOT ; monit summary | grep VAR ; rm /dev/diskhog -f >&1 >> /var/log/server-test.log ; echo "Disk usage testing complete!"

#Test Clients
echo "Testing Clients..." ; monit summary | grep client ; echo "Client testing complete"
